var descriptionarray="HTML structures web pages, defining elements like headings, paragraphs, and images. CSS styles HTML,controlling layout, colors, and fonts, enhancing the visual appeal anduser experience of web pages.";
var showsrcimage="https://cdn.hackr.io/uploads/posts/large/15925654385a8PArotT5.png";
var titlearray=[
    "Add To Card Button Interaction",
    "Add-Remove Button Interaction",
    "Analog Clock",
    "Animated Loading Screen",
    "Animated Upload Model",
    "Blob Effect Micro Interaction",
    "Bouncing Ball Animation",
    "Calculator",
    "Changing Background Gradient Animation",
    "CheckCross Custom Toggle",
    "Confetti Text Effect",
    "Conic Gradient Text Clip",
    "Crazy Button Shape",
    "Credit Card Form",
    "Dot Menu Micro Interaction",
    "Drawing App",
    "Fancy Border Using CSS Variables",
    "Form Validation",
    "Hamburger Menu",
    "Hands On Keyboard",
    "Javascript Dynamic Calendar",
    "Javascript Mouse Animation",
    "Loading Spinner Animation",
    "Menja Game",
    "Movie App",
    "Notify Me Button Animation",
    "Password Generator",
    "Pre Loader Micro Interaction",
    "Product Card Nike",
    "Qr Code Generator",
    "Quiz App",
    "Search Box Micro Interaction",
    "Send Button Animation",
    "Shape Morphing Spinner Animation",
    "Simple Login Form",
    "Smily Slider Emoji",
    "Snow Ball Preloader",
    "Social Icon Hover Effects",
    "Stop Watch",
    "To Do List",
    "Tower Block Game",
];

var showprojectlink=[
"https://github.com/Ayushpateldeveloper/Mini-Projects-AyuPatel/tree/main/Add%20To%20Cart%20Interaction",
"https://github.com/Ayushpateldeveloper/Mini-Projects-AyuPatel/tree/main/Add-Remove%20Button%20Interaction",
"https://github.com/Ayushpateldeveloper/Mini-Projects-AyuPatel/tree/main/Analog%20Clock",
"https://github.com/Ayushpateldeveloper/Mini-Projects-AyuPatel/tree/main/Animated%20Loading%20Screen",
"https://github.com/Ayushpateldeveloper/Mini-Projects-AyuPatel/tree/main/Animated%20Upload%20Model",
"https://github.com/Ayushpateldeveloper/Mini-Projects-AyuPatel/tree/main/Blob%20Effect%20Micro%20Interaction",
"https://github.com/Ayushpateldeveloper/Mini-Projects-AyuPatel/tree/main/Bouncing%20Ball%20Animation",
"https://github.com/Ayushpateldeveloper/Mini-Projects-AyuPatel/tree/main/Calculator",
"https://github.com/Ayushpateldeveloper/Mini-Projects-AyuPatel/tree/main/Changing%20Background%20Gradient%20Animation",
"https://github.com/Ayushpateldeveloper/Mini-Projects-AyuPatel/tree/main/CheckCross%20Custom%20Toggle",
"https://github.com/Ayushpateldeveloper/Mini-Projects-AyuPatel/tree/main/Confetti%20Text%20Effect",
"https://github.com/Ayushpateldeveloper/Mini-Projects-AyuPatel/tree/main/Conic%20Gradient%20Text%20Clip",
"https://github.com/Ayushpateldeveloper/Mini-Projects-AyuPatel/tree/main/Crazy%20Button%20Shape",
"https://github.com/Ayushpateldeveloper/Mini-Projects-AyuPatel/tree/main/Credit%20Card%20Form",
"https://github.com/Ayushpateldeveloper/Mini-Projects-AyuPatel/tree/main/Dot%20Menu%20Micro%20Interaction",
"https://github.com/Ayushpateldeveloper/Mini-Projects-AyuPatel/tree/main/Drawing%20App",
"https://github.com/Ayushpateldeveloper/Mini-Projects-AyuPatel/tree/main/Fancy%20Border%20Using%20CSS%20Variables",
"https://github.com/Ayushpateldeveloper/Mini-Projects-AyuPatel/tree/main/Form%20Validation",
"https://github.com/Ayushpateldeveloper/Mini-Projects-AyuPatel/tree/main/Hamburger%20Menu",
"https://github.com/Ayushpateldeveloper/Mini-Projects-AyuPatel/tree/main/Hands%20On%20Keyboard",
"https://github.com/Ayushpateldeveloper/Mini-Projects-AyuPatel/tree/main/Javascript%20Dynamic%20Calender",
"https://github.com/Ayushpateldeveloper/Mini-Projects-AyuPatel/tree/main/Javascript%20Mouse%20Animation",
"https://github.com/Ayushpateldeveloper/Mini-Projects-AyuPatel/tree/main/Loading%20Spinner%20Animation",
"https://github.com/Ayushpateldeveloper/Mini-Projects-AyuPatel/tree/main/Menja%20Game",
"https://github.com/Ayushpateldeveloper/Mini-Projects-AyuPatel/tree/main/Movie%20App",
"https://github.com/Ayushpateldeveloper/Mini-Projects-AyuPatel/tree/main/Notify%20Me%20Button%20Animation",
"https://github.com/Ayushpateldeveloper/Mini-Projects-AyuPatel/tree/main/Password%20Generator",
"https://github.com/Ayushpateldeveloper/Mini-Projects-AyuPatel/tree/main/Pre%20Loader%20Micro%20Interaction",
"https://github.com/Ayushpateldeveloper/Mini-Projects-AyuPatel/tree/main/Product%20Card%20Nike",
"https://github.com/Ayushpateldeveloper/Mini-Projects-AyuPatel/tree/main/Qr%20Code%20Generator",
"https://github.com/Ayushpateldeveloper/Mini-Projects-AyuPatel/tree/main/Quiz%20App",
"https://github.com/Ayushpateldeveloper/Mini-Projects-AyuPatel/tree/main/Search%20Box%20Micro%20Interaction",
"https://github.com/Ayushpateldeveloper/Mini-Projects-AyuPatel/tree/main/Send%20Button%20Animation",
"https://github.com/Ayushpateldeveloper/Mini-Projects-AyuPatel/tree/main/Shape%20Morphing%20Spinner%20Animation",
"https://github.com/Ayushpateldeveloper/Mini-Projects-AyuPatel/tree/main/Simple%20Login%20Form",
"https://github.com/Ayushpateldeveloper/Mini-Projects-AyuPatel/blob/main/Smily%20Slider%20Emoji",
"https://github.com/Ayushpateldeveloper/Mini-Projects-AyuPatel/tree/main/Snow%20Ball%20Preloader",
"https://github.com/Ayushpateldeveloper/Mini-Projects-AyuPatel/tree/main/Social%20Icon%20Hover%20Effects",
"https://github.com/Ayushpateldeveloper/Mini-Projects-AyuPatel/tree/main/Stop%20Watch",
"https://github.com/Ayushpateldeveloper/Mini-Projects-AyuPatel/tree/main/To%20Do%20List",
"https://github.com/Ayushpateldeveloper/Mini-Projects-AyuPatel/tree/main/Tower%20Block%20Game",
];
var projectpreview=[
"Add To Cart Interaction/index.html",
"Add-Remove Button Interaction/index.html",
"Analog Clock/index.html",
"Animated Loading Screen/index.html",
"Animated Upload Model/index.html",
"Blob Effect Micro Interaction/index.html",
"Bouncing Ball Animation/index.html",
"Calculator/index.html",
"Changing Background Gradient Animation/index.html",
"CheckCross Custom Toggle/index.html",
"Confetti Text Effect/index.html",
"Conic Gradient Text Clip/index.html",
"Crazy Button Shape/index.html",
"Credit Card Form/index.html",
"Dot Menu Micro Interaction/index.html",
"Drawing App/index.html",
"Fancy Border Using CSS Variables/index.html",
"Form Validation/index.html",
"Hamburger Menu/index.html",
"Hands On Keyboard/index.html",
"Javascript Dynamic Calender/index.html",
"Javascript Mouse Animation/index.html",
"Loading Spinner Animation/index.html",
"Menja Game/index.html",
"Movie App/index.html",
"Notify Me Button Animation/index.html",
"Password Generator/index.html",
"Pre Loader Micro Interaction/index.html",
"Product Card Nike/index.html",
"Qr Code Generator/index.html",
"Quiz App/index.html",
"Search Box Micro Interaction/index.html",
"Send Button Animation/index.html",
"Shape Morphing Spinner Animation/index.html",
"Simple Login Form/index.html",
"Smily Slider Emoji/index.html",
"Snow Ball Preloader/index.html",
"Social Icon Hover Effects/index.html",
"Stop Watch/index.html",
"To Do List/index.html",
"Tower Block Game/index.html",
];
var dynamic = document.querySelector('.container');  
for (var i = 0; i < titlearray.length; i++) {
  var fetch = document.querySelector('.container').innerHTML;  
  dynamic.innerHTML = ` 
 
  <div class="card">
         <img src="${showsrcimage}" alt="Add To Card Button Animation">
         <h3>${titlearray[i]}</h3>
         <p>
             ${descriptionarray}</p>
         <div class="buttons">
             <button><a href="${showprojectlink[i]}"><span>Show Me Code</span></a></button>
             <button><a href="${projectpreview[i]}"><span>Preview</span></a></button>                 
         </div>

 </div>` + fetch ; 
} 
